### ISSUE TITLE
Subdirectories are not processed

### ISSUE THREAD

**Issue by grandehombre** [jonycheung/Dead-Simple-LESS-Watch-Compiler#2]
I have a directory called css which contains LESS and CSS files, as well as another directory (libs).
It looks like the directory recursion part is not working.
None of the files in libs are processed,

Looking at the code

line 60:
=============================================================
          callback.pending -= 1;
          done = callback.pending === 0;
          if (!enoent) {
            if (options.ignoreDotFiles && path.basename(f)[0] === '.') return done && callback(null, callback.files);
           /* this causes the problem? */
          if (options.filter && options.filter(f, stat)) return done && callback(null, callback.files); 
            callback.files[f] = stat;
            if (stat.isDirectory()) {
              walk(f, options, callback);
            }else{
              initCallback&&initCallback(f);
            }
=============================================================

the filter check is done before it checks if the current entry is a directory. The filter will fail it because it does not have a correct 'extension', so subdirectories never get processed.

I changed it to
line 62:
=============================================================
          if (!enoent) {
            if (stat.isDirectory()) {
				callback.files[f] = stat;
				walk(f, options, callback, initCallback);    // <------- Also note I added the 4th param!!
            }else{
	            if (options.ignoreDotFiles && path.basename(f)[0] === '.') return done && callback(null, callback.files);
				if (options.filter && options.filter(f, stat)) return done && callback(null, callback.files);
	            callback.files[f] = stat;
				initCallback && initCallback(f);
            }
=============================================================
Note that adding the 4th param to walk() makes it also process the subdir files at startup.

Now that the subdirectory scan is fixed, another problem pops up.
Assume the following dir structure:
work_dir
work_dir/css
work_dir/css/sub1

if this script is run like this:
                   node "less-watch-compiler.js" css css

the css files found in css/sub1 will be compiled and the resulting css will be placed in work_dir/css!

In other words, the file [work_dir/css/sub1/dooda.less]  will be compiled into [work_dir/css/dooda.css] instead of [work_dir/css/sub1/dooda.css]

The solution is to create the output file in the same place the .LESS file was found in.
This also requires changing the script as follows

==========================================
	var extension = getFileExtension(file);
	var command = '';

	var outFilename = file.replace(/\s+/g,"\\ ");
	outFilename = outFilename.replace('.less', '.css');  
	if (extension === 'less') {
		command = "lessc " + file.replace(/\s+/g,"\\ ") + " " + outFilename;
==========================================

This is probably not the correct way to submit changes but I did not want to alter the actual source stored here.
If you are familiar with the process of modifying the source in this repository, please apply these updates.

Cheers,
Nick

**Comment by jonycheung** [comment]
Hi @grandehombre

I have made some significant updates just now to this library and incorporated most of your suggestions here. Thanks again.
