### ISSUE TITLE
Changes to files that are imported are not propagated

### ISSUE THREAD

**Issue by jfbrennan** [jonycheung/Dead-Simple-LESS-Watch-Compiler#5]
An example:

I have a mixins.less file that has my favorite color stored in a variable. My footer.less file imports the mixins file so it can use that color variable. When I change my favorite color in mixins I have to manually force footer to recompile.

I would expect the compiler to recompile the files that import files that have changed.

**Comment by jonycheung** [comment]
Sorry for the late reply. If your files were in subdirectories, they were not picked up due to an error. It is fixed now. Let me know if this fixes your problem.
