### ISSUE TITLE
Feature Request/Idea

### ISSUE THREAD

**Issue by NoahJW** [jonycheung/Dead-Simple-LESS-Watch-Compiler#6]
Nice job on this! Works beautifully.

Here's one thing that would make it even better for my use—and likely others' as well: It would great if the watcher looked in sub-directories as well. This would let me jump around inside of my Less subfolders without having to rerun the watcher.

Other than that though, great tool! Thanks a lot for taking the time to put this one together.

**Comment by jonycheung** [comment]
Hi, not watching sub-directories is a bug. I've just updated and fixed it. Give it a try.
